import { Resend } from 'resend';

const resend = process.env.RESEND_API_KEY 
  ? new Resend(process.env.RESEND_API_KEY) 
  : null;

interface EmailOptions {
  to: string;
  subject: string;
  html: string;
  attachments?: {
    filename: string;
    content: Buffer;
  }[];
}

export const EmailService = {
  async sendEmail({ to, subject, html, attachments }: EmailOptions) {
    if (!resend) {
      console.warn('⚠️ RESEND_API_KEY is not configured. Email NOT sent.');
      console.log(`[DEBUG] Email to: ${to}, Subject: ${subject}`);
      return false; // Fail gracefully
    }

    try {
      const data = await resend.emails.send({
        from: 'zcrAI <noreply@zcr.ai>', // Or use your own verified domain
        to,
        subject,
        html,
        attachments: html.includes('attachments') ? undefined : attachments, // Handle attachments
      });

      if (data.error) {
        console.error('❌ Resend Error:', data.error);
        return false;
      }

      console.log(`✅ Email sent to ${to}: ${data.data?.id}`);
      return true;
    } catch (error) {
      console.error('❌ Failed to send email:', error);
      return false;
    }
  },

  async sendOTP(to: string, otp: string) {
    const html = `
      <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto;">
        <h2>🔐 Your Login Code</h2>
        <p>Use the following code to complete your login to zcrAI:</p>
        <h1 style="background: #f4f4f5; padding: 20px; text-align: center; letter-spacing: 5px; border-radius: 10px;">
          ${otp}
        </h1>
        <p>This code will expire in 5 minutes.</p>
        <hr />
        <p style="font-size: 12px; color: #71717a;">If you didn't request this, please ignore this email.</p>
      </div>
    `;
    return this.sendEmail({ to, subject: 'Your zcrAI Validation Code', html });
  },

  async sendPasswordReset(to: string, token: string) {
    const resetLink = `https://app.zcr.ai/reset-password?token=${token}`;
    const html = `
      <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto;">
        <h2>🔐 Reset Your Password</h2>
        <p>You requested a password reset. Click the button below to proceed:</p>
        <div style="text-align: center; margin: 30px 0;">
          <a href="${resetLink}" style="background: #000; color: #fff; padding: 12px 24px; border-radius: 6px; text-decoration: none; font-weight: bold;">
            Reset Password
          </a>
        </div>
        <p style="color: #71717a; font-size: 14px;">Or copy this link: <a href="${resetLink}">${resetLink}</a></p>
        <p>This link will expire in 1 hour.</p>
        <hr />
        <p style="font-size: 12px; color: #71717a;">If you didn't request this, please ignore this email.</p>
      </div>
    `;
    return this.sendEmail({ to, subject: 'Reset your zcrAI Password', html });
  },

  /**
   * 🔌 Send Integration Alert Email (Disconnected/Reconnected)
   */
  async sendIntegrationAlert(
    to: string, 
    integrationName: string, 
    status: 'disconnected' | 'reconnected',
    errorMessage?: string
  ) {
    const isDown = status === 'disconnected';
    const emoji = isDown ? '🔴' : '🟢';
    const statusText = isDown ? 'Disconnected' : 'Reconnected';
    const color = isDown ? '#ef4444' : '#22c55e';
    
    const html = `
      <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; background: #18181b; padding: 30px; border-radius: 12px;">
        <div style="text-align: center; margin-bottom: 20px;">
          <span style="font-size: 48px;">${emoji}</span>
        </div>
        <h2 style="color: #fff; text-align: center; margin: 0 0 10px;">
          Integration ${statusText}
        </h2>
        <div style="background: #27272a; padding: 20px; border-radius: 8px; border-left: 4px solid ${color};">
          <p style="color: #a1a1aa; margin: 0 0 10px; font-size: 14px;">Integration Name</p>
          <p style="color: #fff; margin: 0; font-size: 18px; font-weight: bold;">${integrationName}</p>
          ${errorMessage ? `
            <hr style="border: none; border-top: 1px solid #3f3f46; margin: 15px 0;" />
            <p style="color: #a1a1aa; margin: 0 0 5px; font-size: 14px;">Error Message</p>
            <p style="color: #fbbf24; margin: 0; font-size: 14px;">${errorMessage}</p>
          ` : ''}
        </div>
        <div style="text-align: center; margin-top: 25px;">
          <a href="https://app.zcr.ai/settings/integrations" 
             style="background: ${color}; color: #fff; padding: 12px 30px; border-radius: 6px; text-decoration: none; font-weight: bold; display: inline-block;">
            ${isDown ? 'Check Integration' : 'View Status'}
          </a>
        </div>
        <p style="color: #71717a; font-size: 12px; text-align: center; margin-top: 25px;">
          This alert was generated by zcrAI at ${new Date().toLocaleString()}
        </p>
      </div>
    `;
    
    const subject = `${emoji} [zcrAI] ${integrationName} ${statusText}`;
    return this.sendEmail({ to, subject, html });
  },

  /**
   * ⏰ Send Token Expiry Alert Email
   */
  async sendTokenExpiryAlert(
    to: string, 
    integrationName: string, 
    daysUntilExpiry: number,
    expiresAt: Date
  ) {
    const isUrgent = daysUntilExpiry <= 1;
    const emoji = isUrgent ? '🚨' : '⏰';
    const urgencyText = isUrgent ? 'URGENT: ' : '';
    const color = isUrgent ? '#ef4444' : '#f59e0b';
    
    const html = `
      <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; background: #18181b; padding: 30px; border-radius: 12px;">
        <div style="text-align: center; margin-bottom: 20px;">
          <span style="font-size: 48px;">${emoji}</span>
        </div>
        <h2 style="color: #fff; text-align: center; margin: 0 0 10px;">
          ${urgencyText}Token Expiring Soon
        </h2>
        <div style="background: #27272a; padding: 20px; border-radius: 8px; border-left: 4px solid ${color};">
          <p style="color: #a1a1aa; margin: 0 0 10px; font-size: 14px;">Integration</p>
          <p style="color: #fff; margin: 0; font-size: 18px; font-weight: bold;">${integrationName}</p>
          <hr style="border: none; border-top: 1px solid #3f3f46; margin: 15px 0;" />
          <p style="color: #a1a1aa; margin: 0 0 5px; font-size: 14px;">Expires In</p>
          <p style="color: ${color}; margin: 0; font-size: 24px; font-weight: bold;">
            ${daysUntilExpiry} day${daysUntilExpiry === 1 ? '' : 's'}
          </p>
          <p style="color: #71717a; margin: 5px 0 0; font-size: 12px;">
            (${expiresAt.toLocaleDateString()} ${expiresAt.toLocaleTimeString()})
          </p>
        </div>
        <div style="text-align: center; margin-top: 25px;">
          <a href="https://app.zcr.ai/settings/integrations" 
             style="background: ${color}; color: #fff; padding: 12px 30px; border-radius: 6px; text-decoration: none; font-weight: bold; display: inline-block;">
            Renew Token Now
          </a>
        </div>
        <p style="color: #71717a; font-size: 12px; text-align: center; margin-top: 25px;">
          Please renew your API key/token to avoid service interruption.
        </p>
      </div>
    `;
    
    const subject = `${emoji} [zcrAI] ${urgencyText}${integrationName} token expires in ${daysUntilExpiry} day${daysUntilExpiry === 1 ? '' : 's'}`;
    return this.sendEmail({ to, subject, html });
  },
  /**
   * 📧 Send User Invitation Email
   */
  async sendInvite(to: string, tempPassword: string, name?: string) {
    const loginUrl = 'https://app.zcr.ai/login';
    const html = `
      <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; background: #18181b; padding: 30px; border-radius: 12px;">
        <div style="text-align: center; margin-bottom: 20px;">
          <span style="font-size: 48px;">👋</span>
        </div>
        <h2 style="color: #fff; text-align: center; margin: 0 0 10px;">
          Welcome to zcrAI${name ? `, ${name}` : ''}!
        </h2>
        <p style="color: #a1a1aa; text-align: center; font-size: 16px;">
          You have been invited to join the platform.
        </p>

        <div style="background: #27272a; padding: 20px; border-radius: 8px; border-left: 4px solid #3b82f6; margin: 25px 0;">
          <p style="color: #a1a1aa; margin: 0 0 8px; font-size: 14px;">Your Temporary Credentials</p>
          
          <div style="margin-bottom: 15px;">
            <span style="color: #71717a; font-size: 12px; display: block; margin-bottom: 4px;">Email</span>
            <span style="color: #fff; font-family: monospace; font-size: 16px;">${to}</span>
          </div>
          
          <div>
            <span style="color: #71717a; font-size: 12px; display: block; margin-bottom: 4px;">Temporary Password</span>
            <span style="color: #fff; font-family: monospace; font-size: 18px; background: #000; padding: 4px 8px; border-radius: 4px;">${tempPassword}</span>
          </div>
        </div>

        <div style="text-align: center; margin-top: 30px;">
          <a href="${loginUrl}" 
             style="background: #3b82f6; color: #fff; padding: 14px 32px; border-radius: 6px; text-decoration: none; font-weight: bold; display: inline-block;">
            Login & Set Password
          </a>
        </div>
        
        <p style="color: #71717a; font-size: 12px; text-align: center; margin-top: 25px;">
          Please change your password immediately after logging in.
        </p>
      </div>
    `;

    return this.sendEmail({ 
      to, 
      subject: 'Welcome to zcrAI - Your Login Credentials', 
      html 
    });
  },
  /**
   * 📊 Send Weekly Smart Digest
   */
  async sendSmartDigest(
    to: string, 
    data: {
      alertCount: number;
      criticalCount: number;
      roiTimeSaved: number;
      topThreats: Array<{ name: string; count: number }>;
      periodStart: Date;
      periodEnd: Date;
    }
  ) {
    const formatTime = (minutes: number) => {
        if (minutes < 60) return `${minutes}m`;
        return `${(minutes / 60).toFixed(1)}h`;
    };

    const html = `
      <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; background: #18181b; padding: 30px; border-radius: 12px; border: 1px solid #27272a;">
        <div style="text-align: center; margin-bottom: 25px;">
           <h2 style="color: #fff; margin: 0;">🛡️ Weekly Security Brief</h2>
           <p style="color: #a1a1aa; font-size: 14px; margin-top: 5px;">
             ${data.periodStart.toLocaleDateString()} - ${data.periodEnd.toLocaleDateString()}
           </p>
        </div>

        <!-- KPI Cards -->
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin-bottom: 25px;">
            <div style="background: #27272a; padding: 15px; border-radius: 8px; text-align: center;">
                <div style="color: #a1a1aa; font-size: 12px; text-transform: uppercase;">Total Alerts</div>
                <div style="color: #fff; font-size: 24px; font-weight: bold;">${data.alertCount}</div>
            </div>
            <div style="background: #27272a; padding: 15px; border-radius: 8px; text-align: center;">
                <div style="color: #ef4444; font-size: 12px; text-transform: uppercase;">Critical Blocking</div>
                <div style="color: #ef4444; font-size: 24px; font-weight: bold;">${data.criticalCount}</div>
            </div>
        </div>

        <!-- ROI Section -->
        <div style="background: linear-gradient(45deg, #3b82f61a, #8b5cf61a); border: 1px solid #3b82f633; padding: 20px; border-radius: 8px; margin-bottom: 25px; text-align: center;">
            <div style="color: #60a5fa; font-size: 12px; text-transform: uppercase; letter-spacing: 1px;">AI Value Generated</div>
            <div style="color: #fff; font-size: 32px; font-weight: bold; margin: 10px 0;">${formatTime(data.roiTimeSaved)}</div>
            <div style="color: #a1a1aa; font-size: 12px;">Engineering time saved via automation this week.</div>
        </div>

        <!-- Top Threats -->
        <div style="margin-bottom: 25px;">
            <h3 style="color: #d4d4d8; font-size: 16px; border-bottom: 1px solid #3f3f46; padding-bottom: 10px;">Top Detected Threats</h3>
            <table style="width: 100%; border-collapse: collapse;">
                ${data.topThreats.map(threat => `
                    <tr>
                        <td style="padding: 10px 0; color: #a1a1aa; font-size: 14px; border-bottom: 1px solid #27272a;">${threat.name}</td>
                        <td style="padding: 10px 0; color: #fff; font-weight: bold; font-size: 14px; text-align: right; border-bottom: 1px solid #27272a;">${threat.count}</td>
                    </tr>
                `).join('')}
                ${data.topThreats.length === 0 ? '<tr><td colspan="2" style="padding: 20px 0; text-align: center; color: #52525b; font-style: italic;">No significant threats detected.</td></tr>' : ''}
            </table>
        </div>

        <div style="text-align: center; margin-top: 30px;">
           <a href="https://app.zcr.ai/dashboard" style="background: #fff; color: #000; padding: 12px 24px; border-radius: 6px; text-decoration: none; font-weight: bold; font-size: 14px;">View Full Report</a>
        </div>
      </div>
    `;

    return this.sendEmail({ 
        to, 
        subject: `🛡️ Security Brief: ${formatTime(data.roiTimeSaved)} Saved`, 
        html 
    });
  }
};

