import puppeteer, { type Browser } from 'puppeteer';
import { DashboardService } from './dashboard.service';
import { AlertService } from './alert.service';
import { CaseService } from './case.service';

export class ReportService {
  private static browser: Browser | null = null;

  /**
   * Get or create Puppeteer browser instance (singleton)
   */
  private static async getBrowser(): Promise<Browser> {
    if (!this.browser) {
      this.browser = await puppeteer.launch({
        headless: true,
        args: [
          '--no-sandbox',
          '--disable-setuid-sandbox',
          '--disable-dev-shm-usage', // Prevent memory issues
        ]
      });
    }
    return this.browser;
  }

  /**
   * Generate Dashboard Summary PDF
   */
  static async generateDashboardPDF(tenantId: string, options?: {
    startDate?: string;
    endDate?: string;
    title?: string;
  }): Promise<Buffer> {
    const data = await DashboardService.getSummary(tenantId, {
      startDate: options?.startDate,
      endDate: options?.endDate
    });

    const html = this.renderDashboardTemplate(data, options);
    return await this.htmlToPDF(html);
  }

  /**
   * Generate Alert Report PDF
   */
  static async generateAlertReportPDF(tenantId: string, filters?: {
    severity?: string[];
    status?: string[];
    limit?: number;
  }): Promise<Buffer> {
    const alerts = await AlertService.list({
      tenantId,
      severity: filters?.severity,
      status: filters?.status,
      limit: filters?.limit || 100
    });

    const html = this.renderAlertTemplate(alerts);
    return await this.htmlToPDF(html);
  }

  /**
   * Generate Case Report PDF
   */
  static async generateCaseReportPDF(caseId: string, tenantId: string): Promise<Buffer> {
    const caseDetail = await CaseService.getById(caseId, tenantId);
    const html = this.renderCaseTemplate(caseDetail);
    return await this.htmlToPDF(html);
  }

  /**
   * Convert HTML to PDF using Puppeteer
   */
  private static async htmlToPDF(html: string): Promise<Buffer> {
    const browser = await this.getBrowser();
    const page = await browser.newPage();
    
    try {
      await page.setContent(html, { waitUntil: 'networkidle0' });
      
      const pdf = await page.pdf({
        format: 'A4',
        printBackground: true,
        margin: {
          top: '20mm',
          right: '15mm',
          bottom: '20mm',
          left: '15mm'
        }
      });
      
      return Buffer.from(pdf);
    } finally {
      await page.close();
    }
  }

  /**
   * Dashboard HTML template
   */
  private static renderDashboardTemplate(data: any, options?: any): string {
    const title = options?.title || 'Security Dashboard Report';
    const now = new Date().toLocaleString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });

    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>${title}</title>
        <style>${this.getBaseStyles()}</style>
      </head>
      <body>
        <div class="header">
          <h1>${title}</h1>
          <p class="subtitle">Generated on ${now}</p>
          ${options?.startDate ? `<p class="subtitle">Period: ${options.startDate} to ${options.endDate}</p>` : ''}
        </div>

        <div class="section">
          <h2>Alert Summary</h2>
          <div class="metric-grid">
            <div class="metric-card">
              <div class="metric-value">${data.total || 0}</div>
              <div class="metric-label">Total Alerts</div>
            </div>
            <div class="metric-card">
              <div class="metric-value severity-critical">${data.critical || 0}</div>
              <div class="metric-label">Critical</div>
            </div>
            <div class="metric-card">
              <div class="metric-value severity-high">${data.high || 0}</div>
              <div class="metric-label">High</div>
            </div>
            <div class="metric-card">
              <div class="metric-value severity-medium">${data.medium || 0}</div>
              <div class="metric-label">Medium</div>
            </div>
          </div>
        </div>

        <div class="footer">
          <p>Generated by zcrAI Security Operations Platform</p>
          <p class="confidential">CONFIDENTIAL - For Internal Use Only</p>
        </div>
      </body>
      </html>
    `;
  }

  /**
   * Alert Report HTML template
   */
  private static renderAlertTemplate(alerts: any[]): string {
    const now = new Date().toLocaleString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });

    const alertRows = alerts.map(alert => `
      <tr>
        <td><span class="severity-badge severity-${alert.severity}">${alert.severity.toUpperCase()}</span></td>
        <td>${alert.title}</td>
        <td>${alert.source}</td>
        <td>${alert.status}</td>
        <td>${new Date(alert.createdAt).toLocaleDateString()}</td>
      </tr>
    `).join('');

    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>Alert Report</title>
        <style>${this.getBaseStyles()}</style>
      </head>
      <body>
        <div class="header">
          <h1>Alert Report</h1>
          <p class="subtitle">Generated on ${now}</p>
          <p class="subtitle">Total Alerts: ${alerts.length}</p>
        </div>

        <div class="section">
          <table class="alert-table">
            <thead>
              <tr>
                <th>Severity</th>
                <th>Title</th>
                <th>Source</th>
                <th>Status</th>
                <th>Created</th>
              </tr>
            </thead>
            <tbody>
              ${alertRows || '<tr><td colspan="5" style="text-align:center">No alerts found</td></tr>'}
            </tbody>
          </table>
        </div>

        <div class="footer">
          <p>Generated by zcrAI Security Operations Platform</p>
          <p class="confidential">CONFIDENTIAL - For Internal Use Only</p>
        </div>
      </body>
      </html>
    `;
  }

  /**
   * Case Report HTML template
   */
  private static renderCaseTemplate(caseData: any): string {
    const now = new Date().toLocaleString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });

    const commentsHtml = caseData.comments?.map((comment: any) => `
      <div class="comment">
        <div class="comment-header">
          <strong>${comment.userEmail || 'Unknown User'}</strong>
          <span class="comment-date">${new Date(comment.createdAt).toLocaleString()}</span>
        </div>
        <div class="comment-content">${comment.content}</div>
      </div>
    `).join('') || '<p>No comments</p>';

    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>Case Report: ${caseData.title}</title>
        <style>${this.getBaseStyles()}</style>
      </head>
      <body>
        <div class="header">
          <h1>Case Report: ${caseData.title}</h1>
          <p class="subtitle">Generated on ${now}</p>
          <p class="subtitle">Case ID: ${caseData.id}</p>
        </div>

        <div class="section">
          <h2>Case Details</h2>
          <div class="case-info">
            <div class="info-row">
              <span class="info-label">Status:</span>
              <span class="info-value"><span class="status-badge status-${caseData.status}">${caseData.status}</span></span>
            </div>
            <div class="info-row">
              <span class="info-label">Severity:</span>
              <span class="info-value"><span class="severity-badge severity-${caseData.severity}">${caseData.severity?.toUpperCase()}</span></span>
            </div>
            <div class="info-row">
              <span class="info-label">Priority:</span>
              <span class="info-value">${caseData.priority || 'N/A'}</span>
            </div>
            <div class="info-row">
              <span class="info-label">Created:</span>
              <span class="info-value">${new Date(caseData.createdAt).toLocaleString()}</span>
            </div>
          </div>
          
          <div class="description-section">
            <h3>Description</h3>
            <p>${caseData.description || 'No description provided'}</p>
          </div>
        </div>

        <div class="section">
          <h2>Investigation Timeline</h2>
          ${commentsHtml}
        </div>

        <div class="footer">
          <p>Generated by zcrAI Security Operations Platform</p>
          <p class="confidential">CONFIDENTIAL - For Internal Use Only</p>
        </div>
      </body>
      </html>
    `;
  }

  /**
   * Base CSS styles for all reports
   */
  private static getBaseStyles(): string {
    return `
      * { margin: 0; padding: 0; box-sizing: border-box; }
      body { 
        font-family: 'Segoe UI', 'Helvetica Neue', Arial, sans-serif; 
        color: #2c3e50; 
        line-height: 1.6;
        font-size: 12pt;
      }
      
      /* Header */
      .header { 
        text-align: center; 
        padding: 40px 0 30px; 
        border-bottom: 3px solid #3498db; 
        margin-bottom: 40px; 
      }
      .header h1 { font-size: 28pt; color: #2c3e50; font-weight: 600; }
      .subtitle { font-size: 10pt; color: #7f8c8d; margin-top: 8px; }
      
      /* Sections */
      .section { margin: 30px 0; page-break-inside: avoid; }
      .section h2 { 
        font-size: 18pt; 
        color: #2c3e50; 
        margin-bottom: 20px; 
        border-left: 4px solid #3498db; 
        padding-left: 15px; 
        font-weight: 600;
      }
      .section h3 { 
        font-size: 14pt; 
        color: #34495e; 
        margin: 20px 0 10px; 
        font-weight: 600;
      }
      
      /* Metrics Grid */
      .metric-grid { 
        display: grid; 
        grid-template-columns: repeat(4, 1fr); 
        gap: 15px; 
        margin: 20px 0; 
      }
      .metric-card { 
        background: #f8f9fa; 
        padding: 20px; 
        border-radius: 8px; 
        text-align: center;
        border: 1px solid #e0e0e0;
      }
      .metric-value { font-size: 32pt; font-weight: 700; color: #2c3e50; }
      .metric-label { font-size: 10pt; color: #7f8c8d; margin-top: 8px; text-transform: uppercase; }
      
      /* Severity Colors */
      .severity-critical { color: #e74c3c !important; }
      .severity-high { color: #e67e22 !important; }
      .severity-medium { color: #f39c12 !important; }
      .severity-low { color: #3498db !important; }
      .severity-info { color: #95a5a6 !important; }
      
      /* Severity Badges */
      .severity-badge {
        display: inline-block;
        padding: 4px 12px;
        border-radius: 4px;
        font-size: 9pt;
        font-weight: 600;
        text-transform: uppercase;
      }
      .severity-badge.severity-critical { background: #fee; color: #c0392b; }
      .severity-badge.severity-high { background: #fef5e7; color: #d68910; }
      .severity-badge.severity-medium { background: #fef9e6; color: #b97d10; }
      .severity-badge.severity-low { background: #ebf5fb; color: #2874a6; }
      
      /* Status Badges */
      .status-badge {
        display: inline-block;
        padding: 4px 12px;
        border-radius: 4px;
        font-size: 9pt;
        font-weight: 600;
        text-transform: capitalize;
        background: #e8f4f8;
        color: #2874a6;
      }
      .status-badge.status-open { background: #e8f8f5; color: #138d75; }
      .status-badge.status-closed { background: #f4ecf7; color: #6c3483; }
      
      /* Alert Table */
      .alert-table { 
        width: 100%; 
        border-collapse: collapse; 
        margin: 20px 0;
      }
      .alert-table thead { background: #34495e; color: white; }
      .alert-table th { 
        padding: 12px; 
        text-align: left; 
        font-weight: 600;
        font-size: 10pt;
      }
      .alert-table td { 
        padding: 10px 12px; 
        border-bottom: 1px solid #e0e0e0;
        font-size: 10pt;
      }
      .alert-table tbody tr:hover { background: #f8f9fa; }
      
      /* Case Information */
      .case-info { margin: 20px 0; }
      .info-row { 
        display: flex; 
        padding: 10px 0; 
        border-bottom: 1px solid #e0e0e0; 
      }
      .info-label { 
        font-weight: 600; 
        width: 150px; 
        color: #34495e;
        font-size: 10pt;
      }
      .info-value { 
        flex: 1;
        font-size: 10pt;
      }
      
      .description-section { 
        margin: 20px 0; 
        padding: 15px; 
        background: #f8f9fa; 
        border-radius: 6px;
        border-left: 3px solid #3498db;
      }
      
      /* Comments */
      .comment { 
        margin: 15px 0; 
        padding: 15px; 
        background: #f8f9fa; 
        border-radius: 6px;
        border-left: 3px solid #95a5a6;
      }
      .comment-header { 
        display: flex; 
        justify-content: space-between; 
        margin-bottom: 8px;
        font-size: 10pt;
      }
      .comment-date { color: #7f8c8d; font-size: 9pt; }
      .comment-content { 
        color: #2c3e50; 
        line-height: 1.6;
        font-size: 10pt;
      }
      
      /* Footer */
      .footer { 
        margin-top: 60px; 
        padding-top: 20px; 
        border-top: 1px solid #bdc3c7; 
        text-align: center; 
        color: #7f8c8d;
        font-size: 9pt;
      }
      .confidential { 
        color: #e74c3c; 
        font-weight: 600; 
        margin-top: 8px;
        font-size: 10pt;
      }
      
      /* Print Optimization */
      @media print {
        body { print-color-adjust: exact; -webkit-print-color-adjust: exact; }
      }
    `;
  }

  /**
   * Cleanup browser instance
   */
  static async cleanup(): Promise<void> {
    if (this.browser) {
      await this.browser.close();
      this.browser = null;
    }
  }
}
